name: Node.js CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.15.0'
      # Install Dev Dependencies
      - run: npm install --dev
      # Installed Dependencies
      - run: npm install
      # Run the Build command that came with the Mod Template
      - run: npm run build --if-present
      # Run tests
      - run: npm test
